### ISSUE TITLE
project restructuration with latest nCore version

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#11]
the ideal project structure would be like this:

```
/app
    /controllers
    /repositories
    /validations
    /views
    /routes.js
/libs
    /helpers
/dependency.json
/core.js
/db.js
```

Raynos talked about its support in the latest version and gave this gist:
https://gist.github.com/fa80552ebce80c9f8ab5

**Comment by ralt** [comment]
Why the `/helpers` folder when there is nothing else in the `/libs` folder? Isn't it just another folder for nothing?

**Comment by Raynos** [comment]
```
require("ncore/modules/core")({
    uri: require("path").join(__dirname, "app"),
    dependencyMapper: {
        jsonUri: require("path").join(__dirname, "dependency.json")
    }
})
```

Might work if your lucky.

**Comment by tbergeron** [comment]
@Ralt This is the folder we talked about together last week [ https://github.com/tbergeron/ThinAir/commit/0b25be495c01bcd5f1ecdf7f74d0de024f4743cd#commitcomment-1316016 ]

@Raynos Thanks for the snippet, I'm gonna try it out and give news back to you! But should I update to nCore's latest version before trying it out?

**Comment by Raynos** [comment]
@tbergeron the only way you can use the latest ncore is git cloning it into node_modules or having

`"ncore": "git://github.com/raynos/ncore.git"`

in package.json, I still need to play with it more before it's ready to go.

**Comment by tbergeron** [comment]
@Raynos it seems to make some kind of infinite loop for the moment, but I may have way more testing to do hehe :P

It's going on on this branch https://github.com/tbergeron/ThinAir/tree/ncore-restructure

**Comment by tbergeron** [comment]
@Raynos amidoinitrite? https://github.com/tbergeron/ThinAir/blob/ncore-restructure/dependency.json

**Comment by Raynos** [comment]
I think the file URI should be local to the dependy.Jain file. see the ncore unit tests

**Comment by tbergeron** [comment]
@Raynos I dunno if you meant that I'd need to put dependency.json file on the same level as the app folder such as:

``` javascript
require("ncore/modules/core")({
    uri: require("path").join(__dirname, "app"),
    dependencyMapper: {
        jsonUri: require("path").join(__dirname, "app", "dependency.json")
    }
});

```

If so, then it's not working.

I'm looking at nCore's current unit tests which does the same in:
https://github.com/Raynos/ncore/blob/master/test/dependencyMapper.js

Tell me if that's what you meant.

Thanks again.

EDIT:
This
https://github.com/tbergeron/ThinAir/blob/67b5121b535ef4cd42a9b594d2e4eb4dac156fb3/libs/dependency.json

ALMOST work, dependencies are working except for those out of libs/ (I decided to put dependency.json in libs/ instead of app/ since it's a part of ThinAir and not the user's app).

So the only files that does not work (but I receive no file not found errors only "Cannot call method 'registerRoutes' of undefined") are those like ../app/routes.js

**Comment by Raynos** [comment]
I meant that the example [dependency.json](https://github.com/Raynos/ncore/blob/master/test/modules/dependency.json) shows that paths are relative to the location of the dependency.json file.

Note you may also need to set the dependencyMapper uri  if it's not the same as uri

```
require("ncore/modules/core")({
    uri: require("path").join(__dirname, "app"),
    dependencyMapper: {
        jsonUri: require("path").join(__dirname, "dependency.json"),
        uri: __dirname,
    }
});
```

**Comment by tbergeron** [comment]
@Raynos okay, now it's getting more interesting, on my latest push I get this error:

``` javascript
module.js:311
    throw err;
          ^
ReferenceError: describe is not defined
    at Object.<anonymous> (/home/tbergeron/Desktop/ThinAir/test/projects.js:7:1)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at loadModule (/home/tbergeron/Desktop/ThinAir/node_modules/ncore/modules/moduleLoader.js:37:26)
    at Object.readOrRecurse [as oncomplete] (/home/tbergeron/Desktop/ThinAir/node_modules/ncore/modules/moduleLoader.js:71:17)
```

with this code:

``` javascript
require("ncore/modules/core")({
    uri: __dirname,
    dependencyMapper: {
        jsonUri: path.join(__dirname, "libs", "dependency.json"),
        uri: __dirname
    }
});
```

Which means that nCore tries to load absolutely everything in /

I must be doing something wrong damn it :-/

Thanks

**Comment by Raynos** [comment]
ncore does load absolutely everything in / which is why I have a src or modules folder.

If you point ncore at / it will load / 

There is a skip parameter which you can set to `/test/` so that it skips the test folder.

```
require("ncore/modules/core")({
    uri: __dirname,
    dependencyMapper: {
        jsonUri: path.join(__dirname, "libs", "dependency.json"),
        uri: __dirname
    },
    moduleLoader: {
        skip: /test/
    }
})
```

**Comment by tbergeron** [comment]
@Raynos wow this is fantastic!

But still, it loads, and loads and loads, damn it.

Here's what I did:

``` javascript
require("ncore/modules/core")({
    uri: __dirname,
    dependencyMapper: {
        jsonUri: path.join(__dirname, "libs", "dependency.json"),
        uri: __dirname
    },
    moduleLoader: {
      skip: /test|public|node_modules|bin/
    }
});

```

It seems to try to reload itself, I tried to put core.js in that list but it still loads forever.

It's almost working, grrr!

Thanks

**Comment by Raynos** [comment]
Would have to debug thoroughly myself. I'll look at it tomorrow, probably best to revert to an older version of ncore.

**Comment by tbergeron** [comment]
@Raynos okay thanks, I'm currently checking things out in moduleLoader, I'll tell you if I find something.

**Comment by tbergeron** [comment]
Just updating that I have tested lots of things and everything runs all the way and well but it hangs somewhere after having parsing the files.. I really dunno why.

**Comment by tbergeron** [comment]
This is perfect, now everything is working fine.
