### ISSUE TITLE
RDBMS support

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#12]
I think it'd be important to support other database engines, since I've been thinking a lot about how MongoDB has not been made to handle "sensitive" data it would be good to support RDBMS engines.

node-orm
https://github.com/dresende/node-orm

EDIT: My main point is being done here:
https://github.com/tbergeron/ThinAir/issues/12#issuecomment-5732688

**Comment by ralt** [comment]
Looks cool, but mongodb support is alpha, is it worth it yet?

**Comment by tbergeron** [comment]
I'm thinking about supporting multiple layers, so mongodb support would use mongo-col/mongodb driver and MySQL/PostgreSQL support would be handled by something else.

The most important point of this process will be to make the framework database agnostic. So that anyone would be able to introduce support to another engine. So supporting ONLY node-orm is not a good idea, since ThinAir would be depend on it.

Without touching any of the "external" API (developers shouldn't have to modify too much of their app's code while switching to another engine).

**Comment by Raynos** [comment]
I highly recommend you avoid an orm and use database drivers directly.

**Comment by tbergeron** [comment]
@Raynos but using mysql/postgresql drivers directly would be very time consuming and since these not json/object based we would have to develop our own orm which may be an even worst idea imo. Tell me what you think.

**Comment by Raynos** [comment]
Don't write your own ORM, use a data source.

You've made the horrible mistake of having only controllers and repositories (a repository is a data source). You need a domain or model that sits between your controller and your repository.

Then you can move domain logic from your controllers and repositories into your domain. You also need two wildly different types of repositories, one with an API that's suitable for a mongoDB database and one with an API that's suitable for a SQL database.

**Comment by tbergeron** [comment]
@Raynos I am currently realizing that I need models... I thought that out would be an advantage at first but now I am changing my mind.

Could you help me to remember why are you hating ORMs so much please?

**Comment by Raynos** [comment]
Because I hate all the things. Do you not know this? My current flavor of the month also says I "hate express"

[Martin fowler has a thread about the recent trend of ORM hate](http://martinfowler.com/bliki/OrmHate.html)

**Comment by tbergeron** [comment]
Thanks for the article, I'm going to read it right now. Why do you hate express now? ;-)

After a lot of thinking, me and a friend came to this conclusion:

NoSQL and RDBMS are two very different worlds.

NoSQL does NOT need ORMs and complicated stuff because it already works almost like one.

But RDBMS needs something to handle SQL queries and give back comprehensive data. Playing directly with SQL would be a real pain in the ass. That's why I'll stay focused on MongoDB support and I'll add SQL support later.

My goal will be to provide a simple way to play with RDBMS, so instead of reinventing the wheel I'll simply support other's work that are already proven and working as intended.

By the way I think the article is totally pertinent as it helped me remembering all the hate I had toward ORMs back when I was using them. The slow factor was incredible and were sometime difficult to get stuff done. Yet for some other reasons I still find them attractive for achieving some goals.
