### ISSUE TITLE
find some good way to handle dates

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#13]
This seems to be kind of good:
http://www.datejs.com/

I don't know if it would be usable server-side though...
This guy seems to have it working:
http://stackoverflow.com/a/6089729/166612

**Comment by ralt** [comment]
What exactly do you want to achieve? On which purpose?

**Comment by Raynos** [comment]
Date.parse works well enough. You only need a date library if you want pretty printing "Last thursday" etc

**Comment by tbergeron** [comment]
@Raynos I believe you're right, after giving Date() docs a second read it seems to be able to make all the things I wanted... 

Nevermind, I got a bit lost hehe.
