### ISSUE TITLE
setup the framework to be able to use server-side libs from client-side

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#14]
I'm wondering if it would be possible to get handlebars' views from the server, from the client?

I'm pretty sure this is possible with nCore...

**Comment by ralt** [comment]
What exactly do you want to achieve? On which purpose?

**Comment by tbergeron** [comment]
@Ralt Like mentioned in the issue, I'd like to be able to get some views from the server's without having to make an AJAX call to get it... Short version: Get views from handlebars from client-side.

**Comment by ralt** [comment]
Have you taken a look at stuff like now.js?

**Comment by tbergeron** [comment]
No, not yet, it seems pretty cool though. I'll study what it would implies to integrate such a thing inside ThinAir.

It could turn out to be a pretty cool thing to do, I wonder what would @Raynos think about that (hate, hate and hate? :P)

Also I don't know if I could put all the "handlebars" module inside "now" hehe, it is still a pretty cool toy it seems.

Thanks!

**Comment by tbergeron** [comment]
I've been playing with it for about an hour and it integrates very badly to ThinAir, oh my god, so much errors. After having read stuff on its github there's a lots of issues with express.

It's sad because I was starting to see great potential in that kind of stuff... I'll try to see how I could replicate such behavior tough...

**Comment by tbergeron** [comment]
I could play directly with socket.io I guess

**Comment by tbergeron** [comment]
I'm having quite a lot of trouble with "502 bad gateway" errors it must be the way I setuped nginx... damn it

**Comment by tbergeron** [comment]
Here's how I finally had it done:
https://github.com/tbergeron/ThinAir/commit/d9af0cb702f0f29a3efc6dd59bc56f87111b5d3d

So now I can:

``` javascript
                //viewName, Context
        getViewFromServer("aViewFromServer", { hello: "world" }, function(data){
            console.log(data);
        });
```

Yay!

**Comment by tbergeron** [comment]
I'll try to introduce this kind of stuff in the project and give the user the right to add more methods to it.
