### ISSUE TITLE
"reactive" methods

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#15]
Here's the deal:

I'd like to introduce methods that would be callable from the client through websockets.

Take that one for example:
https://github.com/tbergeron/ThinAir/blob/63098328ec504b271283b831b147fe8790441ad8/modules/libs/server.js#L30

``` javascript
socket.on('getView', function (name, callback) {
    var viewFilePath = __dirname + "/../app/views/" + name + ".html";

    fs.readFile(viewFilePath, "utf-8", function (err, data) {
        callback(data);
    });
});
```

What it does is that it sends the content of a view through websockets.

So basically what I want is that the user would be able to add more of these kind of "reactive methods".

But I don't know where I should put them. I mean, I don't want to create a whole new concept with a new directory, etc because these methods would be related to a certain domain most of the time. (Example: getUser()  would play in the user repository so it should be in something related to that domain)

It would be cool to say, make "x" method reactive friendly so I could say that getUser method in Users.js, make it availaible to the client. But I don't know how I should do it.

Any advices are welcome.

**Comment by tbergeron** [comment]
After discussing with @Ralt:

It would be good to make a sockets.js file that would be injected in controllers/repositories with nCore and then developers could make any methods "client-callable" without duplicating any code.

https://gist.github.com/2768898

**Comment by Raynos** [comment]
dnode. Use dnode.

Alternatively use specific modules. For example I have a "reactive" mongo module and a observable module that does RPC under the hood to call server modules automatically. 

It's trivial to implement a renderView(name, data, cb) using RPC

**Comment by tbergeron** [comment]
@Raynos thx for the input, I'll look at dnode,

After giving it a quick look it seems to use socket.io? Why should I add another abstraction layer over socket.io?

I mean, what are the pros/cons of directly using socket.io vs dnode?

Thanks!

**Comment by Raynos** [comment]
dnode (RPC) -> socket.io (events) -> websocket (messages) -> TCP 

dnode is just one more abstraction layer, you already have two. dnode does RPC very well, specifically passing function references over the wire and calling arbitary callbacks

**Comment by tbergeron** [comment]
I'll look a bit more on dnode, but so far here's what I came up with:
https://github.com/tbergeron/ThinAir/wiki/Reactive-Methods

You can see the code in the reactive-methods branch.

**Comment by tbergeron** [comment]
Only stuff left to do would be to check for security holes, for example: the parameters JSON object should only contain flat values and nothing dynamic at all.
