### ISSUE TITLE
use node-browserify to pipe client JS from the server

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#16]
I dunno if it's a good idea but it sounds like one to me.
- Create a client-side JS file structure on the server-side:
  /modules/app/client-js (suggest a better name please!) would contain all the client-side js crap (jQuery-LOL-ish files)
- Use node-browserify to bundle and pipe the JS to the client
- ???
- PROFIT!!!

Tell me what you guys think about it, I for myself believe that:
- it would be good performance-wise for the client 
- it would be cool to be able to use require() for client-side javascript
- the whole "logic" of the app would be located under the same directory (/modules/app) which is always a good idea IMO.

https://github.com/substack/node-browserify

**Comment by ralt** [comment]
This'd be nice, really. Now, I'm confused after reading [this post](http://tagneto.blogspot.fr/2012/05/requirejs-20-released-onward-amd.html) about require.js 2.0.

**Comment by Raynos** [comment]
The original idea with ncore is that it does this for you

You simply create a folder containing ncore modules, tell ncore they are client side modules and it will bundle, browserify them and pipe them to the client.

Furthermore the original ncore idea had the notion of client / server and shared folders. Which allows you to share code between server and client.

This isn't implemented properly yet in ncore 2.0

**Comment by tbergeron** [comment]
@Ralt The article is very good, so using only browserify wouldn't be enough? Should I use RequireJS?

@Raynos, the use case description you gave me was delightful, until I read: is not implemented yet in 2.0... ;-( So I'm a bit lost now, will you implement it soon?

**Comment by Raynos** [comment]
It's implemented in 1.0. 2.0 is under active development.

Go look at fyp or ncore boilerplate to see how to use browserify.
