### ISSUE TITLE
pros/cons of removing express from the project

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#20]
While upgrading to 0.8, I had to use the latest version of express which brings many new dependencies and some breaking changes.

It's been a while since I started thinking about building the parts of express that I use in ThinAir. So I'd like to bring the pros and cons about removing express from the project.

Don't get me wrong, I don't want to re-invent the wheel too much. I just want to build some simple solutions that would be built and optimized to be used in ThinAir.

Here's some pros and cons I thought myself:

Pros:
- Total control over dependencies, so more reliable updates/upgrades;
- Re-usable packages (I'd npm publish every part of it);
- ThinAir would become a full-blown framework instead of a express-based framework;

Cons:
- Time consuming;
- Surely more complicated than what I have in mind;

Also, I'd like to make some list of what I'll have to build such as:
- router
- template engine support
- logger
- cookie parser

If anyone has an idea, or something to add, do not hesitate!

/tommy

**Comment by Raynos** [comment]
Look at [routil](https://github.com/Raynos/routil)

I plan to modularize everything that is in lib into seperate npm modules.

Use:
- [routes](https://github.com/aaronblohowiak/routes.js) for templating, 
- [templar](https://github.com/isaacs/templar) for templates and [templar-hogan](https://github.com/Raynos/templar-hogan)
- logger just pick something of npm like winston or roll your own
- cookie parser use [routil-cookie](https://github.com/Raynos/routil-cookie)

**Comment by tbergeron** [comment]
Interesting! Thanks, I'll play with it.

**Comment by Raynos** [comment]
@tbergeron there are a ton of tools. I use the ones above and have only used [debug](https://github.com/visionmedia/debug) for logging so far

**Comment by tbergeron** [comment]
Wow, this is going to be easier that I thought hehe.

Thanks for sharing those tools!

**Comment by Raynos** [comment]
@tbergeron as always, give feedback on the libraries / techniques / APIs over [node.js chat room](http://chat.stackoverflow.com/rooms/642/node-js). You can also read [raynos-blog](https://github.com/Raynos/raynos-blog)

**Comment by tbergeron** [comment]
@Raynos routes are now handled by routes.js and it's working very fine! https://github.com/tbergeron/ThinAir/commit/bbddf095230ebcf8d0547818ca58864508a38a22
