### ISSUE TITLE
introduce routil-cookie to thinair express-less

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#22]

**Comment by Raynos** [comment]
mongodb-based cookies are not cookies but sessions.

Routil doesn't have a session handler yet, I'm going to implement one at some point.

**Comment by tbergeron** [comment]
oh ok, do you have something to suggest me for mongodb-based sessions then?

edit: should I use connect?

**Comment by Raynos** [comment]
my suggestion for mongodb based sessions is that you wait a day and hope that I've released routil-session by then. I'm writing the code as we speak

**Comment by tbergeron** [comment]
@Raynos perfect! I'll wait :-D

**Comment by tbergeron** [comment]
@Raynos is there any reason why I should introduce routil-cookie once that routil-session will be introduced? Is there any use for cookies alone?

**Comment by Raynos** [comment]
@tbergeron I don't think there is a use for cookies outside of session. Arguably you may want to use them as tracking cookies down the line.

**Comment by tbergeron** [comment]
I may introduce them later if someone needs them but so far I'm going to keep it out.
