### ISSUE TITLE
introduce new template engine to thinair

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#25]
I liked handlebars, so I guess I'm going to re-introduce it. It looks quite easy using templar.

**Comment by Raynos** [comment]
You can use hogan instead of handlebars with templar-hogan if you want

**Comment by tbergeron** [comment]
I love handlebars' supplementary features, so I may base myself on your templar-hogan to make a templar-handlebars though :P

**Comment by tbergeron** [comment]
using handlebars with routil and templar has been a breeze!
