### ISSUE TITLE
introduce sessions to thinair express-less

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#27]
I guess the easy way is to use connect but I'm still unsure about that.

**Comment by Raynos** [comment]
[session.js](https://gist.github.com/11f37eeccfd02744a1e9)

Untested gist. Implementing your own session system is easy.

I'll need another day for documentation / unit tests / mongodb store

**Comment by Raynos** [comment]
@tbergeron [mongodb store for that session library](https://gist.github.com/11f37eeccfd02744a1e9#file_mongo_db_store.js)

**Comment by Raynos** [comment]
I implemented the [mongo-store](https://github.com/Raynos/mongo-store) properly and started the [session implementation](https://github.com/Raynos/routil-session)

**Comment by Raynos** [comment]
@tbergeron [working example with routil-session](https://github.com/Raynos/routil-session/blob/master/example/example.js)

So it took 4 days. I was kind of busy

**Comment by tbergeron** [comment]
@Raynos very nice! thanks. I've got some questions though:
- How do you specify connection infos? Must I specify infos for mongostore or mongo-col?

Is this alright:

```

var Session = require("routil-session"),
    MongoStore = require('mongo-store'),
    session = Session({
        store: new MongoStore({
                    collection: require("mongo-col")("sessions"),
                    db: process.env['MONGODB_DATABASE'],
                    host: process.env['MONGODB_HOST'],
                    port: process.env['MONGODB_PORT'],
                    username: process.env['MONGODB_USER'],
                    password: process.env['MONGODB_PASSWORD']
                })
    });
```

Thanks again.

**Comment by Raynos** [comment]
@tbergeron the mongo-col collection object is already connect to a mongodb database. So you just need to pass in the collection and that's it.

As for debugging.

You can try 

```
require("mongo-col")("sessions", yourOwnMongoDbDatabaseInstance, function (err, collection) {
    // handle err or do stuff with collection
})
```

**Comment by Raynos** [comment]
@tbergeron and for the love of god. Don't use the `new` keyword.

**Comment by tbergeron** [comment]
@Raynos Concerning the new keyword, on an afterthought it's right that it does absolutely nothing in comparison to directly using the syntax without the keyword? (Maybe except for real objects?)

**Comment by Raynos** [comment]
@tbergeron it's confusing to use the `new` keyword. It hurts readability because it's completely wrong. And it's also slower then calling it directly.

There's just no need for it. At all

**Comment by tbergeron** [comment]
@Raynow when you say "yourOwnMongoDbDatabaseInstance" how could I get one? Usually I use mongo-col and I specify the database name where you talked about the db instance, is it what you were talking about?

So far so good, I implemented routil-session inside my controllers it looks like this:

```

    create: function(req, res, params) {
        this.createSession(res, { foo: "data!" }, function(err) {
            console.log('created! ' + err);
        });
    },

    get: function(req, res, params) {
        this.getSession(req, function(err, data) {
            console.log('session data:');
            console.log(data);
        });
    },

    delete: function(req, res, params) {
        this.destroySession(req, res, function(err) {
            console.log('deleted! ' + err);
        });
    }
```

But the get returns absolutely nothing yet. Any idea?

**Comment by Raynos** [comment]
@tbergeron try it with memory-store to see whether its a mongo-store or routil-session issue.

your own mongodb database instance would be created using the native mongo driver

```
var Db = require("mongodb").Db
var server = new Db(...)
```

**Comment by tbergeron** [comment]
@Raynos I tried this:

```
var routil = require('routil'),
    Session = require("routil-session"),
    db = require('mongodb').Db,
    Server = require('mongodb').Server,
    dbInstance = new db('db_name', new Server('hostname', port)),
    session = Session({
        store: require('mongo-store')({
            collection: require('mongo-col')('sessions', dbInstance)
        })
    });
```

But it still doesn't return nothing when I try to get the session data.

**Comment by Raynos** [comment]
@tbergeron try

`session = Session()`

That will default to the memory-store instead of the mongo-store.

This way we see whether its a session or mongo issue

**Comment by tbergeron** [comment]
@Raynos ok.

Damn, nothing gets log'd this way either.

**Comment by tbergeron** [comment]
If you want to look at how I implemented it:
https://github.com/tbergeron/ThinAir/blob/express-less/libs/controllers.js
https://github.com/tbergeron/ThinAir/blob/express-less/app/controllers/home.js

**Comment by Raynos** [comment]
@tbergeron you realise if no session data is set that the result is `null` right?

**Comment by tbergeron** [comment]
@Raynos yes but isn't it the job of this part:

```
        this.createSession(res, { foo: "data!" }, function(err) {
            console.log('created! ' + err);
        });
```

?

**Comment by Raynos** [comment]
@tbergeron correct, if that route is run then session data should be stored.

I'll debug this later on.

**Comment by tbergeron** [comment]
@Raynos yeah, I run the /create then I run the /get to test it out.

Okay, keep me updated. thanks!

**Comment by Raynos** [comment]
@tbergeron also try running the example in the routil-session project locally. If that works try and mess with your code until it's the same as the example.

If the example is broken then I failed

**Comment by tbergeron** [comment]
@Raynos Damn it the example works. I'll double-check my code out.

**Comment by tbergeron** [comment]
@Raynos I think I found the culprit. Maybe when I merge the session object with my controllers' object, something wrong happens and it doesn't store sessions properly. I'll try a different approach.

**Comment by tbergeron** [comment]
@Raynos for some reason Session() doesn't like to be manipulated. If I interact directly with Session(); it looks like it works but if I do anything like implementing them in my controllers it's always null and I can't even see the methods when I console.log'd it.

It may be because of how my controllers are instanced. I'll keep testing out.

**Comment by tbergeron** [comment]
@Raynos I found something.

Is it normal that when I do:

```
var Session = require("routil-session"),
    session = Session();

    console.log(session);
```

It returns only {} and not all your functions you're returning? (getSession, etc)

**Comment by tbergeron** [comment]
@Raynos Update:

Doing this in your example.js gives me the object with its methods:

```
var Session = require("..")
    , session = Session()

console.log(session);
```

Doing this somewhere else using a require for the package name, gives me empty object {}:

```
var Session = require('routil-session'),
    session = Session();

console.log(session);
```

**Comment by Raynos** [comment]
@tbergeron republisehd as 0.1.1 try again

**Comment by tbergeron** [comment]
@Raynos you're my savior! it's working fine now! thanks!

**Comment by Raynos** [comment]
@tbergeron sorry for publishing broken code >_<

**Comment by tbergeron** [comment]
@Raynos haha no problem, I was wondering what must I do if:
I createSession;
I getSession;
I want to change the content from getSession and put it back into sessions? Do I re-use createSession for this?

**Comment by Raynos** [comment]
@tbergeron create session just writes a session object for the entire user to the database. I consider it bad practice to alter the session object but feel free to replace it with a new one

**Comment by tbergeron** [comment]
@Raynos But let's say the session contains:

```
{
    user: 'Raynos',
    lastActivity: '2012-07-18 10:26:00'
}
```

And now you make a new comment and I must update lastActivity to now?

**Comment by Raynos** [comment]
@tbergeron my session is simple.

`createSession(res, userId, callback)`

```
function getUser(req, callback) {
    getSession(req, function (err, userId) {
        User.find({ userId: userId }, callback)
    })
}
```

**Comment by tbergeron** [comment]
@Raynos, good point. that indicts that everything should be stored in the database instead of the sessions.

**Comment by Raynos** [comment]
@tbergeron as it should. It also indicates that the session contains the user object and the session is a simple call to the database.

Furthermore you can optimize this by storing the sessionId in the cookie directly in the user database rather then in a seperate database table.

This would involve the notion of a `mongo-user-store`. I should write that.

**Comment by tbergeron** [comment]
Holy shit. I really don't know why, I was moving stuff around and then re-tried this:

```
var pd = require('pd'),
    routil = require('routil'),
    Session = require("routil-session");

var Controllers = {
    // creates a basic controller
    createController: function(content) {
        console.log(Session());
        return pd.extend(Object.create({}), routil, Session(), content, {
            // sends a template
            sendTemplate: function(req, res, name, params) {
                // preventing templar to throw an error if there's no data
                if (!params) params = {};

                this.template(req, res, name + '.html', params);
            }
        });
    }
};

module.exports = Controllers;
```

And still it gives me {} what the hell?!

**Comment by Raynos** [comment]
@tbergeron `npm cache clear` ? `rm node_modules -r` `npm install` ?

**Comment by tbergeron** [comment]
@Raynos I can't believe it, I'm sure it worked yesterday at least twice. And now still the same  {} as before.

It's got to be something related to nCore. Because if I directly run controllers.js with `Controllers.createController({});` it simply works.

But when the code is running as a whole, it doesn't. Any idea why nCore would prevent this to happen?

**Comment by Raynos** [comment]
@tbergeron is your problem that your creating a new Session object with  a new memory store for each controller?

I don't know what's wrong.

**Comment by tbergeron** [comment]
@Raynos Maybe ultimately it'll be a problem, but so far even if I move the code in another part of the framework, I get always {} as a result from Session().

I'll keep up testing.

**Comment by tbergeron** [comment]
@Raynos I moved it there:
https://github.com/tbergeron/ThinAir/blob/express-less/libs/router.js

And it's still the same. I should try to make a little ncore project to test it in this environment. The router is getting instanced only once, so there shouldn't be a problem with this... Damn, I wonder what the heck is happening.

**Comment by tbergeron** [comment]
@Raynos Found out this:
https://gist.github.com/3145285

It works, but once it's a part of the module it doesn't.

sessions.js is simply this btw:

```
var Session = require('routil-session');
module.exports = Session();
```

UPDATE: For fuck sake, I SWEAR I do absolutely nothing except restarting the app, and now it ALWAYS give me { } there must be something very wrong going on somewhere...

**Comment by tbergeron** [comment]
@Raynos I found that even what I do:

```
var anger = {
    scream: function() { console.log('hello world'); }
};

module.exports = anger;

console.log(anger);
```

Ran alone it logs the right object, but once it's included by nCore it gives `{ }`.

Please tell me I'm dumb and this is normal and there's a reason for it. I'm going insane right now.

**Comment by Raynos** [comment]
@tbergeron it's not normal.

if it's a bug in nCore your allowed to shoot me. commit something to git for me to checkout and i'll play with it.

ncore does inject "proxies" of modules into other modules. however it should not augment module.exports

**Comment by Raynos** [comment]
@tbergeron it does call `bindAll` on the object

I double checked in the console. `bindAll` should not mess with it

**Comment by tbergeron** [comment]
@Raynos You should be able to play with this:
https://github.com/tbergeron/ThinAir/blob/faf0ba4bf2a307ca3f47f956f2c06caffc16e310/libs/router.js
https://github.com/tbergeron/ThinAir/blob/faf0ba4bf2a307ca3f47f956f2c06caffc16e310/test.js

I added comments for you to know what to expect. `test.js` is a sample object, just so you see that a very barebones object doesn't go through nCore in that case.

Concerning `bindAll`, is it supposed to be called since I'm not mentioning this file in `dependencies.json`?

**Comment by Raynos** [comment]
@tbergeron bindAll get's called in ncore as a feature

**Comment by tbergeron** [comment]
@Raynos I know, but I thought it'd get only executed on files mentioned in `dependencies.json`. I guess I'm mistaken hehe :P

**Comment by Raynos** [comment]
@tbergeron cool I'll check it out tonight

**Comment by tbergeron** [comment]
@Raynos Anything I could put my teeth on to help you yet?

**Comment by Raynos** [comment]
@tbergeron sorry :( I've been busy. I'll look at it when im not at work & when im not tired.

**Comment by tbergeron** [comment]
@Raynos no problem, haha don't stress yourself out, I don't want to put pressure on you. I was just wondering if I could do anything since I've got some spare time right now ;-) I'll go play with something else meanwhile..

**Comment by Raynos** [comment]
@tbergeron if you want to play with something else play with mountie & seaport or play with cross browser testing using my testem fork

**Comment by tbergeron** [comment]
hahaha good idea, I'll go check these out ;-)
