### ISSUE TITLE
re-introduce messages to thinair express-less

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#28]

**Comment by Raynos** [comment]
What's a message

**Comment by tbergeron** [comment]
This. https://github.com/tbergeron/ThinAir/blob/master/libs/messages.js ;-)

**Comment by Raynos** [comment]
@tbergeron why would you do that ._.

**Comment by tbergeron** [comment]
@Raynos LOL. Because I find it useful to have some kind of way to flash messages to a user?

But more frankly, I was thinking about it today and I kind of find that piece of code useless. It's easy to use sessions to implement this... Hum you make me re-re-thinking about it now...

**Comment by tbergeron** [comment]
Just finished re-looking at the code and, thanks for challenging me about it, now I find it totally useless. Fuck it hehe.

**Comment by Raynos** [comment]
@tbergeron sessions are stateful :/ they are evil. They are this lump of global state you dump your hacks on.

**Comment by tbergeron** [comment]
@Raynos But then, what would you use to transmit messages?

**Comment by Raynos** [comment]
@tbergeron what messages. Give me a specific use case. How about you pass them along directly rather then grab them from global magic scope

**Comment by tbergeron** [comment]
Holy crap, I guess this is an old PHP kiddie behavior of mine.

I always did it that way because of how I learnt it back in the days, but on a second thought, since the app is always running in the background, I don't need to save stuff to sessions to get it back next time it'll execute (as with PHP).

Forgot what I told you, you are totally right.
