### ISSUE TITLE
create a placeholder directory for helpers/libs

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#29]
Developing apps with the framework I noticed one little issue:
When I needed to put something to reuse it, out of controllers/models/etc I didn't had a directory to place it into.

Maybe a helpers/ directory? I dunno yet... Let's think about it.

**Comment by Raynos** [comment]
@tbergeron the directory your looking for is called node_modules

Learn to write small modules that do single things well and publish them to npm

**Comment by tbergeron** [comment]
I totally agree about the npm part, I should really separate things out and publish them. I couldn't agree more, for some reason I'm having a hard time separating my stuff out damn it. I don't know where to begin.

Do you know any good article explaining the development of a module? (The _correct_ way of doing it). I know about the whole process but maybe just in the wrong order lol.

**Comment by tbergeron** [comment]
@Raynos -oh and by the way, little routil question: how to get the current used http method? let's say from req can I get the method from there? I'd like to be able to do if (req.method == 'get') for example. same for any headers-

NEVERMIND. Just realized how dumb this question was since it isn't about routil but about node itself. Sorry about that.

**Comment by Raynos** [comment]
> I don't know where to begin.

Find a single problem your abstracting. Write a new module for it. Go take a look at all the routil-x modules I wrote

@tbergeron my best advice is you try to create an app from scratch without thinair and without ncore. Then see what pieces of your code are actually useful

**Comment by Raynos** [comment]
@tbergeron [`req.method`](http://nodejs.org/api/http.html#http_request_method), [`req.headers`](http://nodejs.org/api/http.html#http_request_headers)

**Comment by Raynos** [comment]
@tbergeron the reason I recommend using tools like routil instead of express. Is that it actually forces you to learn how to use the `req` and `res` objects http gives you correctly rather then use what ever magic methods express exposes

**Comment by tbergeron** [comment]
@Raynos you've got very good points there. thanks for the advice.

I'm learning a lot since I stopped using express actually...

I'm currently trying to find a way to decode query strings to objects.

I used querystring to decode and it gives me the input fields with their values but the conversion to object part I cannot figure except maybe using regexes...

I'd like something like connect's bodyParser thing.

I want to take the query string or this:

```
{
  "project[name]": "test"
}
```

And convert it into this:

```
{
  "project": {
    "name": "test"
  }
}
```

Any idea of what should I use to make this happen?

**Comment by tbergeron** [comment]
Looking at connect's code, it seems like it takes the query string and JSON.parse's it... wtf.

**Comment by Raynos** [comment]
@tbergeron `var qs = require('querystring'); qs.parse`

@tbergeron [form body](https://github.com/Raynos/routil-body/blob/master/index.js#L30)

**Comment by tbergeron** [comment]
@Raynos that is what I was using:

``` javascript
if (req.method == 'POST') {
    // Converting query string to objects
    var body = '';

    req.on('data', function(chunk) {
        body += chunk.toString();
    });

    req.on('end', function() {
        var decodedBody = querystring.parse(body);

        // merging body inside req
        req = pd.extend(Object.create(req), { body: decodedBody });

        route.fn(req, res, route.params, route.splats);
    });
}
```

routil-body is almost what I'm currently building, but what about the part that converts it to objects?

**Comment by Raynos** [comment]
@tbergeron there is no notion of objects. send valid form encoded data.

**Comment by tbergeron** [comment]
@Raynos I got what I want:

``` javascript

var parseQueryString = function (queryString) {
    var querystring = require('querystring');
    var parsedBody = querystring.parse(queryString);

    // creating body object
    var body = {};

    // loops on properties
    for (var key in parsedBody) {
        var value = parsedBody[key];

        // checks if one contains []
        if (key.indexOf('[') != -1) {
            var splitKey = key.split('[');
            // gets first part to make object name
            var objectName = splitKey[0];
            // gets last part for property name
            var propertyName = splitKey[1].replace(']', '');

            // if object doesn't exist yet, create it
            if (body[objectName] === undefined) {
                body[objectName] = {};
            }

            // assigning value to property
            body[objectName][propertyName] = value;
        } else {
            // if it's a simple value, assign it
            body[key] = value;
        }
    }

    return body;
}
```

Takes `project%5Bname%5D=name&project%5Bauthor%5D=project&date=bleh` and turns it into:

```
{
  "project": {
    "name": "name",
    "author": "project"
  },
  "date": "bleh"
}
```

;-)

**Comment by tbergeron** [comment]
@Raynos I think I got a good idea for a package now! ^^
