### ISSUE TITLE
re-introduce tests to thinair

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#30]
Once everything is working (I know it should be done while developing) I'll need to make a lot more tests to test every part of thinair so that Travis detects any issues with the code at any time.

Tests that should be developed:
- router
- template
- controllers
- repositories
- validators
- reactive methods

**Comment by Raynos** [comment]
@tbergeron if you have skype I can demo my badass testing workflow

**Comment by tbergeron** [comment]
@Raynos I'm testing testem right now, based on routil-session code. A demo would be interesting ;-)

**Comment by tbergeron** [comment]
@Raynos I have skype by the way, username is `tomshreds`.

**Comment by tbergeron** [comment]
@Raynos playing with testem, which framework do you suggest me to use for thinair tests? jasmine, mocha, ?

also: what the heck is tap?

I'm checking https://github.com/airportyh/testem/tree/master/examples/mocha_simple out at this moment.

**Comment by Raynos** [comment]
@tbergeron use testling

**Comment by Raynos** [comment]
@tbergeron  do make sure you add actual assertions to your unit tests and not just logs

**Comment by tbergeron** [comment]
@Raynos good point, I'm still trying to debug the test you made earlier.

I over-simplified it to use simply directly with node to debug it:

``` javascript
var request = require('request'),
    nCoreStart = require("./core")

nCoreStart(startTests)

function startTests() {
    makeRequest("/get", function (err, res, body) {
        console.error('err', err)
        console.error('body', body)
    })
}

function makeRequest(opts, cb) {
    if (typeof opts === 'string') {
        opts = "https://localhost:3000" + opts
    } else {
        opts.uri = "http://localhost:3000" + opts.uri
    }
    request(opts, cb)
}
```

And I still get `[test.js:8] err { [Error: socket hang up] code: 'ECONNRESET' }`

I really don't have a clue of what's going on. Any idea of what I should look for? Usually the app gets started and everything is going fine. I can even open my browser and play with the app, but request() is getting that error... which is weird since at the same time I can play with the app...

**Comment by tbergeron** [comment]
DAMN! From the beginning it was because the first condition, you wrote `https`. I was re-re-re-re-reading it and removed the s and now it works fine. Nevermind now. :-)

**Comment by Raynos** [comment]
@tbergeron https >_< btw.

Note how I've rewriten [test-server](https://github.com/Raynos/test-server#example) inside your test suite. It might be good if you tried using test-server somehow.

**Comment by tbergeron** [comment]
@Raynos To use it, I guess I'd have not to start the framework's server, and use test-server's one instead, right? I'll try to figure out how to do it.

Also, do you have any idea of why this is happening with 0.8.x on travis?
http://travis-ci.org/#!/tbergeron/ThinAir/jobs/1928906

0.6.0 test runs fine.

**Comment by Raynos** [comment]
@tbergeron the idea behind test-server is that simple

```
var app = function (req, res) {
    ...
}

module.exports = app

if (require.main === module) {
    http.createServer(app).listen(PORT)
}
```

**Comment by Raynos** [comment]
@tbergeron and your build error is simple

> Not compatible with your version of node/npm: mongo-col@0.1.7

So go and install the latest version 0.1.16

**Comment by tbergeron** [comment]
@Raynos oh, my bad. Looked at the bottom, damn.

Hum. Not compatible with your version of node/npm: mongo-col@0.1.16

WTF. Isn't there any ignore about that? Is it because in your package.json there's only:

```
"engines": {
        "node": "0.6"
    }
```

EDIT: I sent your a pulled request for it. https://github.com/Raynos/mongo-col/pull/3
?

**Comment by tbergeron** [comment]
Also, except for the test-server bit, what do you think of this test: 
https://github.com/tbergeron/ThinAir/blob/fa64c1452e83624b654091cdbb47371af4f722c1/test/http/sessions.js
?

As for asserts, what do you use? tap-assert?

But, what's the difference between "asserts" and this: `t.equal(body, undefined, "body should be undefined")`? Isn't it the same? (to compare 2 things together)

**Comment by Raynos** [comment]
@tbergeron the `t` object passed to your `test` callback has all the `assert` methods on it.

I recommend you basically use `assert` but get all those methods from `t`

@tbergeron there is no difference between asserts and `t.equal` those are the same thing. The technical difference is that `tap` knows that `t.equal` is an assert of that particular "test callback" with that particular "name" from the `test(name, ...` call which of course shows you slightly nicer reporting

**Comment by Raynos** [comment]
@tbergeron my main recommendation on `test-server` is [the done callback](https://github.com/Raynos/routil-methods/blob/master/test/integration.js#L96) which cleanly kills the http server so the damned process can end. this makes such a difference.

**Comment by tbergeron** [comment]
@Raynos I'll try to use `test-server` for my next tests. It sure looks useful. I'll figure out how to use it since in https://github.com/tbergeron/ThinAir/blob/master/libs/server.js#L17 it starts its own server, I think I should try to detect if it's called for a test or not and if it's for a test then to use test-server and if not then to use its own server.

I guess this is how it's supposed to work, tell me if I'm mistaken. (That's what you've shown ^^)

**Comment by Raynos** [comment]
@tbergeron I personally recommend an app which is a request handler and then an entry point which starts a http server.

I don't know what's the optimum way for this to work with ncore and tests. I have to think about it. 

I need to think harder about making ncore easier to work with, with normal code.

**Comment by tbergeron** [comment]
@Raynos okay yeah, good point. I should separate the framework initializer from the server startup.

**Comment by tbergeron** [comment]
@Raynos Damn, I'm still lost. If I run the test-server, then I'll have to sends the requests to my router to obtain the results. So all the router part from my server.js will be in my test?

Maybe I should create a setUp() method that will starts ^^ and then proceed with my tests?

**Comment by Raynos** [comment]
@tbergeron 

```
// modules/server.js
var requestHandler = function (req, res) {
    ...
}

...

requestHandler.setup = setup
requestHandler.init = init

...

if (require.main === module) {
    http.createServer(requestHandler).listen(PORT)
}

module.exports = requestHandler
```

```
// test/http/foo.js
var server = require("../../modules/server")

testServer(server, startTests)

...
```

That would be the best "option" I can think of right now

**Comment by tbergeron** [comment]
@Raynos The only problem right now, is that I use ncore DI in the requestHandler. And the way you set it up ^^ I can't access `this.router`from requestHandler. I'm trying to figure how I'm going to deal with this.

I got this:

``` javascript
var http = require('http');

var requestHandler = function(req, res) {
    // sending request to router
    router.match(req, res);
};

requestHandler.setup = function(done) {
    if (require.main != module) {
        // if ran from c9, use its port
        process.env.PORT = (process.env.C9_PORT != undefined) ? process.env.C9_PORT : process.env.PORT;

        var router = this.router;

        // starts the server
        var server = http.createServer(requestHandler).listen(process.env.PORT, done);

        // socket.io initialization
        this.sockets.initialize(server);

        return console.log('ThinAir server listening on port ' + process.env.PORT);
    }
}

module.exports = requestHandler;
```

**Comment by tbergeron** [comment]
Got it:

``` javascript
var http = require('http'),
    router = require('./router');

var requestHandler = function(req, res) {
    // sending request to router
    router.match(req, res);
};

requestHandler.setup = function(done) {
    if (require.main != module) {
        // if ran from c9, use its port
        process.env.PORT = (process.env.C9_PORT != undefined) ? process.env.C9_PORT : process.env.PORT;

        // starts the server
        var server = http.createServer(requestHandler).listen(process.env.PORT, done);

        // socket.io initialization
        this.sockets.initialize(server);

        return console.log('ThinAir server listening on port ' + process.env.PORT);
    }
}

module.exports = requestHandler;
```

**Comment by tbergeron** [comment]
@Raynos Yay! https://github.com/tbergeron/ThinAir/blob/98ada00119c3a80aa269123b249dabd2479a989b/test/http/sessions.js

**Comment by Raynos** [comment]
@tbergeron 

> access this.routerfrom requestHandler. I'm trying to figure how I'm going to deal with this.

```
var self = module.exports = requestHandler

function requestHandler(req, res) {
    self.router.match(req, res)
}
```

Functions are objects. ncore injects properties on objects

**Comment by tbergeron** [comment]
@Raynos oh this is awesome. Didn't figured I could do that. Thanks!

**Comment by Raynos** [comment]
@tbergeron 

`nCoreStart(testServer(server, startTests));`

is wrong

```
nCoreStart(function  () {
    testServer(server, startTests)
})
```

is correct

Ideally you want to fetch the `server` proxy that ncore exposes rather then the actual module. But for now I don't think that's an issue

**Comment by tbergeron** [comment]
@Raynos I'll look for ncore's expose to see what I can do.

You're right, it also looks better.

0.6.x is having trouble with the latest changes:
http://travis-ci.org/#!/tbergeron/ThinAir/jobs/1929959

it seems that something is wrong with getting the server

**Comment by Raynos** [comment]
@tbergeron looks like a race condition. See the fix I mention above to call testServer after ncore is ready

**Comment by tbergeron** [comment]
@Raynos ok just pushed it. uh now both crashes lol. http://travis-ci.org/#!/tbergeron/ThinAir/jobs/1929983

it now hangs for some reason.

It seems that the ncore's callback doesn't get called at all.

**Comment by Raynos** [comment]
@tbergeron 

https://github.com/tbergeron/ThinAir/blob/9487d31e5feda32823ffce4eefb915b626703cde/libs/server.js#L9

Your setup is async

```
if (require.main === module) {
    // start server
} else {
    // call done to let ncore know we are done
    done()
}
```

**Comment by tbergeron** [comment]
@Raynos I don't know whats wrong but when I start testem now it says waiting for browser and it doesn't seem to load my tests. Then I press enter, it seems to load but no tests is getting loaded.

But if I switch back to:

``` javascript
nCoreStart(testServer(server, startTests)
```

it works again and the test passes (except for 0.6)

**Comment by Raynos** [comment]
@tbergeron the problem is obvouisly that `ncorestart` callback never gets fired.

You do realise that 

`nCoreStart(testServer(server, startTests))`

is actually

```
var iAmNotAFunction = testServer(server, startTests)
nCoreStart(iAmNotAFunction)
```

The most likely case is that you have an asynchronous setup that never calls `done` just like I mentioned above.

**Comment by tbergeron** [comment]
@Raynos This is right, the function gets called before and then gets passed. This is clear now.

I looked in my whole project, and found only 2 setup function, and these ones now call done().

Does init() needs a done parameter too? UPDATE:  `The optional callback to init will be called after all modules are done with the setup.` so I guess so?

I just can't find out why the callback isn't getting called. Damn it.

Trying to debug from ncore code core's setupModules function next()'s counter is never getting to 0 but only to 3 so I guess that means 3 other modules need setup done to be called...?

**Comment by Raynos** [comment]
@tbergeron commit the current state.

Are you sure you call `done` when `require.main != module` ?

**Comment by Raynos** [comment]
@tbergeron init does not need a done parameter.

the callback to init is part of `Core.init` not `module.init`

**Comment by tbergeron** [comment]
@Raynos ok. commited to master.

**Comment by tbergeron** [comment]
@Raynos I really don't get why I'm supposed to put things that way:
https://github.com/tbergeron/ThinAir/blob/e76a733591c7a74affb2f4945a7d961b9aa9a825/libs/server.js

Since when I call node core.js, require.main != module
And when I call it from the test, require.main === module

Is it supposed to be that way? Because now if I simply start the app the server doesn't get started.

**Comment by Raynos** [comment]
@tbergeron your code doesn't work when you start the app because your `server` file isn't the entry point, core.js is.

Your best bet is to put that code in a method on the server module and then

```
// core.js
if (require.main === module) {
    server.startTheDamnThing()
}
```

I also realize ncore should have some timeout mechanism on the setup done callback so it tells you. "HEY YOU FORGOT THE CALLBACK"

**Comment by tbergeron** [comment]
@Raynos hehe, I'm tracing which aren't setup'd well right now.

just pushed a new commit with things the way you told me.

**Comment by tbergeron** [comment]
@Raynos Does a module NEEDS a setup function? or if there's none it'll get skipped? because I have many modules without setup functions.

**Comment by Raynos** [comment]
@tbergeron 
- if no setup module then it is skipped
- if a setup module and it has no parameters (setup.length === 0) then it is sychronous and done is called for you
- if a setup module has a parameter (setup.length === 1) then that function needs to be called before the init callback fires

**Comment by tbergeron** [comment]
Et voilà! it works now! Thanks!!! :D

**Comment by tbergeron** [comment]
You were right, now Travis runs fine. Amazing.

**Comment by Raynos** [comment]
@tbergeron the only issue is that your starting two http servers in your unit tests I think one from testserver and one from core.

And yes I will [fix this issue with lack of warnings at some point](https://github.com/Raynos/ncore/issues/11). Feel free to fork ncore and implement this patch and test it out to see whether it makes debugging easier for you

**Comment by tbergeron** [comment]
@Raynos Great, I'll give it a try.

I'll check about the servers, I must have messed something up.
