### ISSUE TITLE
Fix tests, again

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#37]
Since ThinAir will be converted to a package, tests will need some rework.

**Comment by tbergeron** [comment]
I think I'm going to simply put the old app/ structure there, and if thinair is called from tests, use it as the main application so tests could run.

**Comment by ralt** [comment]
Uh? What do you mean?

That's the way I see things FYI:

```
node_modules/
    thinair/
        // some files, folders, and:
        tests/
```

In the package.json, add mocha to the `devDependencies`, and test each file separately. If you want some integration tests, then call a file from thinair and test the output, but you shouldn't have to get out of the thinair folder.

**Comment by tbergeron** [comment]
That was only some thinking for myself. I need the old app/ folder which is a basic testing application so tests can run. But since ThinAir has become a package I removed that app/ folder.

I must re-introduce it, and make some basic handling for tests to run that app/ directory. That's all :P

**Comment by ralt** [comment]
So, that's integration tests. You don't need the app/ folder for unit tests of the methods of thinair :)

Mocha supports integration tests by emulating an environment (mocking) IIRC.
