### ISSUE TITLE
make ThinAir work as a global npm install

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#38]
So far the package has been working as a per-project install.

But I need it to work globally. So people could do `npm install -g thinair` and enjoy all that CLI goodness.

**Comment by ralt** [comment]
Do you know how to do this? Or you need a little quick tutorial? (very. quick.)

**Comment by tbergeron** [comment]
@Ralt I'm almost done doing it, but please tell me. It may help me, maybe there's something I don't know yet! Thanks!

**Comment by ralt** [comment]
Oh, I was just going to tell you about the `bin` option in the package.json, but I guess you've already found it :-)

**Comment by tbergeron** [comment]
haha yeah already found it. I'm tweaking ncore so it can work globally right now :P

**Comment by tbergeron** [comment]
Making it global is a plain right suicide for the moment. I'll see if it's asked. Because so far it works amazingly fine locally.
