### ISSUE TITLE
Routes helpers

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#40]
Routes helpers will fill the gap between routes and helpers. Quickly explained:

If someone wants to have every request for a single route checked if the client is logged in he'll have to do:

A single function in `helpers/routes.js` (still thinking about the name). So he'll make a `userIsLogged(req, res)` function in there which will return a `boolean`.

And in the `routes.json` he'll add an option to that route:

``` javascript
"/pages": { controller: "page", action: "index", options: { userIsLogged: true } }
```

So that function will get executed and will returns the boolean to the route. Which will give the ability to kick the user out of the app if he's not logged in. Without having too much overhead code in each actions. (No `if (userislogged)` in every damn controllers' action).

That's the main idea.

**Comment by ralt** [comment]
So basically you want what express calls middleware?

**Comment by tbergeron** [comment]
Haha I did not realize that it was like middlewares but yeah it sounds like it.

**Comment by ralt** [comment]
The middlewares don't return true or false however, it uses `next()` to let the request go or something else if something's wrong.
