### ISSUE TITLE
Build Roadmap

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#42]
It would be important to build a small roadmap of where I want to go with the project until the next version.

**Comment by tbergeron** [comment]
Done. https://github.com/Brainpad/ThinAir/wiki/Roadmap

**Comment by ralt** [comment]
Fwiw, I had difficulties maintaining the roadmap in my projects, and ended up linking to the issues tagged with "roadmap", or whatever name you choose.

**Comment by tbergeron** [comment]
That's a good idea actually, thanks for sharing hehe :-)
