### ISSUE TITLE
Modularize

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#46]
@Raynos will be happy to read this.

For 0.5.x I intend to try to modularize ThinAir, making little `thinair-packages`.

I need suggestions though. What should be a module? Here's a quick list:
- Router
- Validators
- Reactive Methods
- Controllers
- Repositories

Any other suggestions?

**Comment by ralt** [comment]
Maybe the CLI should be a "main package", having the other packages as dependencies? It'd be like flatiron does it.

**Comment by tbergeron** [comment]
This is actually a good idea!

That would be the kind of package that glues all the other together. Great point! Thanks

**Comment by Raynos** [comment]
@tbergeron `thinair-packages` is bad. The fact that I namespaced my modules with `routil-` in npm was a big mistake.

The only one I didn't namespace is [redirecter](https://github.com/Raynos/redirecter). I turned [routil itself](https://github.com/Raynos/routil#small-libraries) into a list of links.

I agree with @Ralt that `thinair` can be a CLI.

**Comment by Raynos** [comment]
- ~~Router.~~ Solved problem use routes or mapleTree
- ~~Validators~~ Solved problem use validate
- ~~Reactive Methods~~ What even is this? Is it dnode? Is it streams?
- ~~Controllers~~ Solved problem write your own code.
- ~~Repositories~~ Solved problem use mongo-col
