### ISSUE TITLE
Use JSON for config file

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#48]
It's been a long time since I chose to use globals for config. Back in the day I had only 2-3 things to stuck there but no more.

Also, use NODE_ENV instead of our own global that does the same thing.

**Comment by ralt** [comment]
Heh. A nice trick in loading JSON files is that:

```
var config = require('./config.json');
```

works.

**Comment by tbergeron** [comment]
Yeah I obviously didn't know that back when I started developing ThinAir hehe. Thx!
