### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#7]
i was wondering how to package this, since it's not a "package" but a whole framework...

**Comment by tbergeron** [comment]
If anyone has an idea about how to we should do it, go ahead and tell me!

**Comment by Raynos** [comment]
ncore needs an api to add a npm package to ncore as a bunch of modules. I'm aware that this can't be done cleanly currently.

**Comment by tbergeron** [comment]
Any updates on that?

When you said "I'm aware that this can't be done cleanly currently" did you meant that this could be done?

Thanks

**Comment by Raynos** [comment]
@tbergeron there are two issues here.

Doing something like this in dependencies.json (no clue how to do this optimally)

```
{
    "router.js": {
        "router": "npm@routes@0.0.1"
    }
}
```

The other issue is how do you publish thinair on npm. That can be best solved by modularization and splitting the library from the application.

**Comment by tbergeron** [comment]
After some intensive testing and tweaking, I can say that it shouldn't be that hard to realize.

I made a package with only the `libs` directory in it, renamed `core.js` to `index.js` and tweaked a bit the framework to suit the changes.

Then I modified `moduleLoader.js` to handle complex exceptions (i.e should load content from `app/` but not from `node_modules` except when it's `node_modules/thinair` and not for `node_modules/thinair/node_modules`.

This way it was loading the proper files, but for some reason, it was doing its job fine with `app/` but dependencies in `node_modules/thinair/libs` weren't working. The files were loading but not their dependencies (they were getting passed to core's `injectDependencies` but they hadn't any dependencies in them so nothing was mapped.

That's about it for the moment, not done but still very interesting to see that it's very possible.

You can see my tests in this temporary repo: https://github.com/tbergeron/ThinAirNpm

**Comment by tbergeron** [comment]
@Raynos still no breakthrough on this matter? Working with ThinAir as a package would be so much easier. I'm waiting for this before officially releasing the framework. I tried myself to find a solution but it really doesn't work at all unfortunately... Thanks

**Comment by Raynos** [comment]
@tbergeron modularize the damn thing.

It's trivial to put objects and functions on NPM.

**Comment by tbergeron** [comment]
@Raynos but the thing about ThinAir is that it's a whole. Once separated I can't see an easy way of using it. It's a web development framework, so you'll always need the router, templates, etc..

So users could simply do a index.js with `var ThinAir = require('thinair')` in it. And then simply have to create the app/\* structure. Without having to use module by module all the time.

I'll think about it, but so far I can't see how I could modularize everything and still be able to do what I wrote as the example ^^

If you have any suggestions, please tell me. Thanks

**Comment by ralt** [comment]
Don't you think they should rather do `npm install -g thinair` and use commands such as `thinair create project...`?

**Comment by tbergeron** [comment]
@Ralt that is what I'd love it to be. I made ThinAir so I could quickly build web apps without having to deal with 101 packages dependencies. ThinAir does it for you.

**Comment by tbergeron** [comment]
@Raynos As a second point. Using `ncore` means "you can't push that module to NPM". I don't mean to be rude, don't get me wrong, I'm just looking for a solution.

Thanks @Ralt, I'll need plenty of opinions on this.

**Comment by ralt** [comment]
Since I think I'm going to do the same with tartempion, I've been looking around how to do this.

You don't need an index.js file btw, define this file in the package.json :) (the "bin" option IIRC)

And you can just make the CLI build the folder by copying all the files, solves all the problems.

**Comment by tbergeron** [comment]
@Ralt that's what I intended to do in the end. And about the ìndex.js`you're right, the project would be started like this`thinair start`in the project's directory.

**Comment by tbergeron** [comment]
@Raynos Having talked with @Ralt, he said he uses ncore.constructor, ncore.add & ncore.init

That way I could bypass the main issue of `moduleLoader` that freaks out loading ALL THE THINGS. Don't you think?

I could myself scan for repositories and injects them in controllers without going crazy about other js files in the project.

I started a branch and I'm going to test with this. If you have any suggestions please do tell me. Thanks

**Comment by ralt** [comment]
After thinking about it, you basically want to rewrite `moduleLoader` ^^

Dunno if that's the best solution.

**Comment by tbergeron** [comment]
@Ralt That is what I understood while walking 10 minutes ago damn it. Rewrite the whole thing for the sole purpose of fixing a misbehaviour of it is surely NOT the solution we're looking for.

**Comment by Raynos** [comment]
I don't even know what's going on at all. I don't use ncore much myself anymore.

**Comment by tbergeron** [comment]
@Raynos The problem is that to be able to use a ncore-based project as a package, modulesLoader would have to be able to scan directories without going crazy and load ALL THE THINGS. That's the solution I'm looking for.

Because if I make a ThinAir package, and it is found in ./node_modules/thinair/ then the deps.json will contain path such as ../../app/controllers (since thinair is located in node_modules/thinair) but when I use it like this it goes crazy and scan everything like the node_modules dir itself. And if I add it in the ignores regex, then it just doesn't work since it ignores itself...

I don't want to stop using ncore since it's just so freaking useful to ThinAir. Tell me if I explained it right and if you understand what's going on. Thanks

**Comment by Raynos** [comment]
@tbergeron then use thinair as a core and export that core. Then in your app you somehow export the thinair core into another core.

ncore was not meant for node_modules

**Comment by ralt** [comment]
@Raynos I **clearly** don't understand this sentence:

> then use thinair as a core and export that core. Then in your app you somehow export the thinair core into another core.

Could you clarify a bit?

**Comment by Raynos** [comment]
@Ralt when you have an ncore instance you can add and remove modules from it and init those modules.

You can just export that ncore instance and have your app init those modules and talk to those modules. ncore is just a container for modules

**Comment by ralt** [comment]
I really don't see what you mean, sorry... Maybe you could give an example in pseudo code?

**Comment by tbergeron** [comment]
I literally pulling my hair out on this one. I really can't seem to find a solution. In https://github.com/Brainpad/ThinAirNpm I had started to fiddle with ncore, had ignored lots of directories but it's just not the way to fix this issue.

I'll keep trying until I fall asleep lol. If I ever find something relevant.

EDIT: I just don't get why it's scanning all the damn files even if they aren't declared in `dependencies.json`

**Comment by Raynos** [comment]
@tbergeron the [moduleLoader](https://github.com/Raynos/ncore/blob/master/modules/moduleLoader.js) is 20 lines. Just don't use it and write your own

**Comment by tbergeron** [comment]
@Raynos that's a good point. But how could I write another one and use it and NOT use ncore's one?

I can fork ncore and replace the default with mine though and use this fork in ThinAir.

What should happen in there IMO, is that it should scan ONLY the place mentioned in `dependency.json`

**Comment by Raynos** [comment]
@tbergeron overwrite the default.

**Comment by tbergeron** [comment]
@Raynos I began and so far it scans the right files now. But it just run, injections never happen, though setup() gets called. Tell me what you think: https://github.com/Brainpad/ThinAirNpm/blob/master/node_modules/thinair/node_modules/ncore/modules/moduleLoader.js#L29

UPDATE:
Some of them are injected but not every of them. But every files gets passed.

Is there any importance about load order?

Also, is the name passed important? (the name passed in moduleLoader.core.add(name, module))

**Comment by tbergeron** [comment]
Finally. I got that working. npm package is on its way.

Look what I've done here:
https://github.com/tbergeron/ncore

This could only work for ThinAir though. But I'll try to make it work globally and make a pull request with it.

Thanks all for the help.

**Comment by tbergeron** [comment]
@Raynos Here's a question about the inner-working of ncore:

Could you tell me the order of calls that happen when a module gets injected in dependencyMapper?
Like core.makeInterface, core.makeProxy, etc. I'd like to know the whole process from `dependency.json` to the assignation of `this.property`. (`property` being the filename)

Because for one of my modules, it gets injected but when I try to use it in another module the `this.propery` is assigned but returns undefined. That module leads to a function, so it should return a proxyModule function I guess.

It would help me a lot. Thanks, very appreciated.

When it goes into:

``` javascript
var _interface = makeInterface(this, name, module)
```

It returns:

``` javascript
function proxyModule() {
        return module.apply(this, arguments)
}
```

and proxy returns:

``` javascript
function proxyForFunction() {
        return interfaces[name].apply(this, arguments)
}
```

Which is fine.

But when I get to use it the `this.property` === undefined.

**Comment by Raynos** [comment]
@tbergeron https://github.com/Raynos/ncore/blob/master/lib/core.js#L128

**Comment by tbergeron** [comment]
@Raynos I must have broke something because deps is always equal to {} damn it.
