### ISSUE TITLE
build documentation

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ThinAir#9]
1. ✓ General Overview
2. ✓ Routes
3. Controllers
4. Repositories
5. Validations
6. Views
7. Partials
8. Helpers

**Comment by ralt** [comment]
Something came to my mind when I started reviewing the documentation: at the end of each wiki page, there should be a link to the next chapter. It makes navigation easier.

**Comment by tbergeron** [comment]
Good point! Next time I write some I'm going to make that change.Thanks for pointing that out  ;-)

**Comment by tbergeron** [comment]
Here's an example of what I did:

« d.1 General Overview | Table of contents | d.3 Controllers »

**Comment by ralt** [comment]
Good one :)
